using System;

class Program
{
    static void Main()
    {
        byte byteVar1 = 52;
        byte byteVar2 = 655;
        byte byteVar3 = 510;
        byte byteVar4 = 5;
        byte byteVar5 = 78;
        byte byteVar6 = 10010;
        byte byteVar7 = 869;
        byte byteVar8 = 35;
        byte byteVar9 = 58;
        byte byteVar10 = 0;
        byte byteVar11 = 561;
        byte byteVar12 = 150;
        byte byteVar13 = 869;
        byte byteVar14 = 77;
        byte byteVar15 = 7;

        int intVar1 = 87458;
        int intVar2 = -7878;
        int intVar3 = 0;
        int intVar4 = 988749;
        int intVar5 = 94884;
        int intVar6 = -4444;
        int intVar7 = 8748;
        int intVar8 = 08409;
        int intVar9 = 89494;
        int intVar10 = -15;
        int intVar11 = -101;
        int intVar12 = -745;
        int intVar13 = 787878;
        int intVar14 = 99999;
        int intVar15 = -99999;

        float floatVar1 = 3.14f;
        float floatVar2 = -0.001f;
        float floatVar3 = 2.71828f;
        float floatVar4 = 100.5f;
        float floatVar5 = -45.67f;
        float floatVar6 = 0.0f;
        float floatVar7 = 1.618f;
        float floatVar8 = 99.99f;
        float floatVar9 = -33.33f;
        float floatVar10 = 77.0f;
        float floatVar11 = -88.8f;
        float floatVar12 = 123.456f;
        float floatVar13 = -765.432f;
        float floatVar14 = 0.0001f;
        float floatVar15 = -9999.9999f;

        double doubleVar1 = 3.1415926535;
        double doubleVar2 = -0.0000001;
        double doubleVar3 = 2.7182818284;
        double doubleVar4 = 1000.0001;
        double doubleVar5 = -1234.5678;
        double doubleVar6 = 0.0;
        double doubleVar7 = 1.4142135623;
        double doubleVar8 = 9999.9999;
        double doubleVar9 = -1111.1111;
        double doubleVar10 = 12345.6789;
        double doubleVar11 = -98765.4321;
        double doubleVar12 = 0.123456789;
        double doubleVar13 = -0.987654321;
        double doubleVar14 = 1000000.0000001;
        double doubleVar15 = -999999.9999999;

        char charVar1 = 'A';
        char charVar2 = 'B';
        char charVar3 = 'C';
        char charVar4 = 'a';
        char charVar5 = 'b';
        char charVar6 = 'c';
        char charVar7 = '1';
        char charVar8 = '2';
        char charVar9 = '3';
        char charVar10 = '$';
        char charVar11 = '%';
        char charVar12 = '&';
        char charVar13 = '*';
        char charVar14 = '+';
        char charVar15 = '?';

        bool boolVar1 = true;
        bool boolVar2 = false;
        bool boolVar3 = true;
        bool boolVar4 = false;
        bool boolVar5 = true;
        bool boolVar6 = false;
        bool boolVar7 = true;
        bool boolVar8 = false;
        bool boolVar9 = true;
        bool boolVar10 = false;
        bool boolVar11 = true;
        bool boolVar12 = false;
        bool boolVar13 = true;
        bool boolVar14 = false;
        bool boolVar15 = true;

        string stringVar1 = "Hello";
        string stringVar2 = "World";
        string stringVar3 = "CSharp";
        string stringVar4 = "Programming";
        string stringVar5 = "Example";
        string stringVar6 = "Code";
        string stringVar7 = "Console";
        string stringVar8 = "Application";
        string stringVar9 = "Data";
        string stringVar10 = "Types";
        string stringVar11 = "Variables";
        string stringVar12 = "Output";
        string stringVar13 = "Input";
        string stringVar14 = "Function";
        string stringVar15 = "Method";

        Console.WriteLine("Byte:");
        Console.WriteLine($"значение переменной - {byteVar1}");
        Console.WriteLine($"значение переменной - {byteVar2}");
        Console.WriteLine($"значение переменной - {byteVar3}");
        Console.WriteLine($"значение переменной - {byteVar4}");
        Console.WriteLine($"значение переменной - {byteVar5}");
        Console.WriteLine($"значение переменной - {byteVar6}");
        Console.WriteLine($"значение переменной - {byteVar7}");
        Console.WriteLine($"значение переменной - {byteVar8}");
        Console.WriteLine($"значение переменной - {byteVar9}");
        Console.WriteLine($"значение переменной - {byteVar10}");
        Console.WriteLine($"значение переменной - {byteVar11}");
        Console.WriteLine($"значение переменной - {byteVar12}");
        Console.WriteLine($"значение переменной - {byteVar13}");
        Console.WriteLine($"значение переменной - {byteVar14}");
        Console.WriteLine($"значение переменной - {byteVar15}");

        Console.WriteLine("\nInt:");
        Console.WriteLine($"значение переменной - {intVar1}");
        Console.WriteLine($"значение переменной - {intVar2}");
        Console.WriteLine($"значение переменной - {intVar3}");
        Console.WriteLine($"значение переменной - {intVar4}");
        Console.WriteLine($"значение переменной - {intVar5}");
        Console.WriteLine($"значение переменной - {intVar6}");
        Console.WriteLine($"значение переменной - {intVar7}");
        Console.WriteLine($"значение переменной - {intVar8}");
        Console.WriteLine($"значение переменной - {intVar9}");
        Console.WriteLine($"значение переменной - {intVar10}");
        Console.WriteLine($"значение переменной - {intVar11}");
        Console.WriteLine($"значение переменной - {intVar12}");
        Console.WriteLine($"значение переменной - {intVar13}");
        Console.WriteLine($"значение переменной - {intVar14}");
        Console.WriteLine($"значение переменной - {intVar15}");

        Console.WriteLine("\nFloat:");
        Console.WriteLine($"значение переменной - {floatVar1}");
        Console.WriteLine($"значение переменной - {floatVar2}");
        Console.WriteLine($"значение переменной - {floatVar3}");
        Console.WriteLine($"значение переменной - {floatVar4}");
        Console.WriteLine($"значение переменной - {floatVar5}");
        Console.WriteLine($"значение переменной - {floatVar6}");
        Console.WriteLine($"значение переменной - {floatVar7}");
        Console.WriteLine($"значение переменной - {floatVar8}");
        Console.WriteLine($"значение переменной - {floatVar9}");
        Console.WriteLine($"значение переменной - {floatVar10}");
        Console.WriteLine($"значение переменной - {floatVar11}");
        Console.WriteLine($"значение переменной - {floatVar12}");
        Console.WriteLine($"значение переменной - {floatVar13}");
        Console.WriteLine($"значение переменной - {floatVar14}");
        Console.WriteLine($"значение переменной - {floatVar15}");

        Console.WriteLine("\nDouble:");
        Console.WriteLine($"значение переменной - {doubleVar1}");
        Console.WriteLine($"значение переменной - {doubleVar2}");
        Console.WriteLine($"значение переменной - {doubleVar3}");
        Console.WriteLine($"значение переменной - {doubleVar4}");
        Console.WriteLine($"значение переменной - {doubleVar5}");
        Console.WriteLine($"значение переменной - {doubleVar6}");
        Console.WriteLine($"значение переменной - {doubleVar7}");
        Console.WriteLine($"значение переменной - {doubleVar8}");
        Console.WriteLine($"значение переменной - {doubleVar9}");
        Console.WriteLine($"значение переменной - {doubleVar10}");
        Console.WriteLine($"значение переменной - {doubleVar11}");
        Console.WriteLine($"значение переменной - {doubleVar12}");
        Console.WriteLine($"значение переменной - {doubleVar13}");
        Console.WriteLine($"значение переменной - {doubleVar14}");
        Console.WriteLine($"значение переменной - {doubleVar15}");

        Console.WriteLine("\nChar:");
        Console.WriteLine($"значение переменной - {charVar1}");
        Console.WriteLine($"значение переменной - {charVar2}");
        Console.WriteLine($"значение переменной - {charVar3}");
        Console.WriteLine($"значение переменной - {charVar4}");
        Console.WriteLine($"значение переменной - {charVar5}");
        Console.WriteLine($"значение переменной - {charVar6}");
        Console.WriteLine($"значение переменной - {charVar7}");
        Console.WriteLine($"значение переменной - {charVar8}");
        Console.WriteLine($"значение переменной - {charVar9}");
        Console.WriteLine($"значение переменной - {charVar10}");
        Console.WriteLine($"значение переменной - {charVar11}");
        Console.WriteLine($"значение переменной - {charVar12}");
        Console.WriteLine($"значение переменной - {charVar13}");
        Console.WriteLine($"значение переменной - {charVar14}");
        Console.WriteLine($"значение переменной - {charVar15}");

        Console.WriteLine("\nBool:");
        Console.WriteLine($"значение переменной - {boolVar1}");
        Console.WriteLine($"значение переменной - {boolVar2}");
        Console.WriteLine($"значение переменной - {boolVar3}");
        Console.WriteLine($"значение переменной - {boolVar4}");
        Console.WriteLine($"значение переменной - {boolVar5}");
        Console.WriteLine($"значение переменной - {boolVar6}");
        Console.WriteLine($"значение переменной - {boolVar7}");
        Console.WriteLine($"значение переменной - {boolVar8}");
        Console.WriteLine($"значение переменной - {boolVar9}");
        Console.WriteLine($"значение переменной - {boolVar10}");
        Console.WriteLine($"значение переменной - {boolVar11}");
        Console.WriteLine($"значение переменной - {boolVar12}");
        Console.WriteLine($"значение переменной - {boolVar13}");
        Console.WriteLine($"значение переменной - {boolVar14}");
        Console.WriteLine($"значение переменной - {boolVar15}");

        Console.WriteLine("\nString:");
        Console.WriteLine($"значение переменной - {stringVar1}");
        Console.WriteLine($"значение переменной - {stringVar2}");
        Console.WriteLine($"значение переменной - {stringVar3}");
        Console.WriteLine($"значение переменной - {stringVar4}");
        Console.WriteLine($"значение переменной - {stringVar5}");
        Console.WriteLine($"значение переменной - {stringVar6}");
        Console.WriteLine($"значение переменной - {stringVar7}");
        Console.WriteLine($"значение переменной - {stringVar8}");
        Console.WriteLine($"значение переменной - {stringVar9}");
        Console.WriteLine($"значение переменной - {stringVar10}");
        Console.WriteLine($"значение переменной - {stringVar11}");
        Console.WriteLine($"значение переменной - {stringVar12}");
        Console.WriteLine($"значение переменной - {stringVar13}");
        Console.WriteLine($"значение переменной - {stringVar14}");
        Console.WriteLine($"значение переменной - {stringVar15}");

        Console.ReadKey();
    }
}
